# Generated by Django 2.0.12 on 2021-06-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_register_form_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_form',
            name='add_date',
            field=models.DateField(max_length=10),
        ),
    ]
