# Generated by Django 2.0.12 on 2021-06-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210614_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_form',
            name='id',
        ),
        migrations.AlterField(
            model_name='register_form',
            name='add_date',
            field=models.DateField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
