# Generated by Django 2.0.12 on 2021-06-14 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210614_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_form',
            name='add_date',
            field=models.DateField(default=uuid.uuid1, max_length=10, primary_key=True, serialize=False),
        ),
    ]
